url: https://www.rhentabli.com

# Site settings
title: Rahim Hentabli
email: rhentabli21@gmail.com
description: "Rahim Hentabli's online portfolio as a Software Developer."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://linkedin.com/in/abdelrahim-hentabli
  - title: github
    url: https://github.com/abdelrahim-hentabli

# Postal address (add as many lines as necessary)
address:
  - line: 1424 Everton Pl.
  - line: Riverside, CA 92507

# Build settings
markdown: kramdown
permalink: pretty

# Open Graph Protocol MetaData
opgtitle: Rahim Hentabli
opgtype: website
opgimage: /img/thumbnail.png
opgurl: https://www.rhentabli.com