url: https://www.rhentabli.com

# Site settings
title: Rahim Hentabli
email: rhentabli21@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://linkedin.com/in/abdelrahim-hentabli
  - title: github
    url: https://github.com/abdelrahim-hentabli

# Postal address (add as many lines as necessary)
address:
  - line: 1424 Everton Pl.
  - line: Riverside, CA 92507

# Build settings
markdown: kramdown
permalink: pretty